name: PR Environment Cleanup

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  cleanup-pr-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Destroy PR environment
        working-directory: infrastructure/modules/pr-environment
        run: |
          terraform init
          terraform destroy -auto-approve -var="pr_number=${{ github.event.number }}"

      - name: Comment PR cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            const comment = `## 🧹 PR Environment Cleaned Up

            The temporary environment for PR #${prNumber} has been destroyed to save costs.

            > Cleaned up after PR was ${context.payload.action}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
