name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  sonarcloud:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate API client
        run: npm run api:generate

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check if SonarCloud token exists
        id: check-token
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "token-exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ SONAR_TOKEN not configured - SonarCloud analysis will be skipped"
          else
            echo "token-exists=true" >> $GITHUB_OUTPUT
            echo "✅ SONAR_TOKEN found - proceeding with analysis"
          fi

      - name: SonarCloud Scan
        if: steps.check-token.outputs.token-exists == 'true'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.verbose=true

      - name: SonarCloud Skipped Notice
        if: steps.check-token.outputs.token-exists == 'false'
        run: |
          echo "::notice::SonarCloud analysis was skipped because SONAR_TOKEN is not configured."
          echo "::notice::To enable SonarCloud analysis, please add SONAR_TOKEN to repository secrets."
          echo "::notice::See docs/SONARCLOUD_SETUP.md for setup instructions."
